"""markdown

Revision ID: bef23f359574
Revises: 0c55b6f2ea09
Create Date: 2020-01-15 11:50:20.701091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef23f359574'
down_revision = '0c55b6f2ea09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'body_html')
    # ### end Alembic commands ###
